### ISSUE TITLE
Cant install plugins or update wordpress using this theme

### ISSUE THREAD

**Issue by ivan-vilches** [elementor/hello-theme-child#30]
Days ago i log as admin on my wp site using child hello theme and i cant update anything and i cant install plugins, i manually installed last wp 5.9.1 and the problems is there. 
When i change to default theme twenty eleven i can install plugins butwhen i back to hello child theme the problem i still there, my permissions are ok on folders, i am using elementor free and i didnt renew yet elementor pro.
Thanks for any help

**Comment by kwsim539** [comment]
Hmm. That strange.  I have the latest version of the child theme and on WP 5.9.1 and I just got done adding content to my site with no issues.

**Comment by kwsim539** [comment]
Do you have code in your child theme that might not agree with WP 5.9.1? Check your error logs.

**Comment by ivan-vilches** [comment]
i found define('DISALLOW_FILE_MODS',true); 
set to true on the main hello theme not the child, why is that? i set to false and now back to normally.
thanks

**Comment by kwsim539** [comment]
You may want to replace/update your theme. Because I've searched the entire theme codebase downloaded from the repo, [[()]([](https://github.com/elementor/hello-theme))](https://github.com/elementor/hello-theme) and found no instance of define('DISALLOW_FILE_MODS',true); in any of the *.php files. I also searched my entire theme folder on my site and again found no instance of define('DISALLOW_FILE_MODS',true);. It would also be helpful if you could be more specific as to a location and/or screenshot would help where you found this define function than a general mention that it was found.

![image](https://user-images.githubusercontent.com/8410150/155463219-d59f7945-fe85-46ca-a844-fab5f036ad3e.png)

![image](https://user-images.githubusercontent.com/8410150/155462672-286987f2-e09b-4885-8bb3-07f032c7bb07.png)

![image](https://user-images.githubusercontent.com/8410150/155463072-3b18562a-7fc7-42b5-bcab-38a1ff27614b.png)

**Comment by rami-elementor** [comment]
The original Hello Child Theme doesn't have the code you mentioned: `define('DISALLOW_FILE_MODS',true);`

You need to contact the developer that created the child theme for your site, maybe he added some additional functionality to the child theme. Ask the developer to remove the limiting functionality that prevents you from install plugins and updating WordPress.
